# Apresentação editorial. Fontes e proveniência visual: docs/about-sources.md.
wlv_about_link <- function(href, label, ...) {
  tags$a(href = href, target = "_blank", rel = "noopener", ..., label)
}
wlv_about_person <- function(name, href, photo = NULL, photo_class = NULL) {
  tags$article(class = paste("wlv-about-person", if (is.null(photo)) "wlv-about-person-text"),
    if (!is.null(photo)) tags$img(src = photo, alt = name, class = photo_class, loading = "lazy"),
    tags$div(tags$h3(name), wlv_about_link(href, l("about2.profile"))))
}

TABPANEL <- tabPanel(l("tab_name.about"), value = "about",
  tags$main(class = "wlv-about",
    tags$section(class = "wlv-about-hero",
      tags$div(class = "wlv-about-hero-content",
        tags$p(class = "wlv-about-kicker", l("about2.kicker")),
        tags$h1(l("about2.title")),
        tags$p(class = "wlv-about-lead", l("about2.intro")),
        tags$div(class = "wlv-actions",
          actionButton("about_map", l("about.map"), class = "btn-primary", icon = icon("globe")),
          actionButton("about_indicators", l("about.indicators"), icon = icon("chart-line"))))),
    tags$div(class = "wlv-about-content",
      tags$section(class = "wlv-about-intro",
        tags$div(tags$p(class = "wlv-about-kicker", l("about2.project_kicker")),
          tags$h2(l("about2.project_title"))),
        tags$div(tags$p(l("about2.project_text")),
          tags$p(l("about2.project_network")),
          wlv_about_link("https://worldlabourvalues.org/", l("about2.project_link")))),
      tags$section(class = "wlv-about-questions",
        tags$h2(l("about2.questions")),
        tags$div(class = "wlv-about-topics",
          tags$article(tags$span(class = "wlv-about-topic-icon", icon("people-group")),
            tags$h3(l("about2.labour_title")), tags$p(l("about2.labour_text"))),
          tags$article(tags$span(class = "wlv-about-topic-icon", icon("industry")),
            tags$h3(l("about2.production_title")), tags$p(l("about2.production_text"))),
          tags$article(tags$span(class = "wlv-about-topic-icon", icon("globe")),
            tags$h3(l("about2.trade_title")), tags$p(l("about2.trade_text"))))),
      tags$section(class = "wlv-about-research",
        tags$div(tags$p(class = "wlv-about-kicker", l("about2.research_kicker")),
          tags$h2(l("about2.research_title")), tags$p(l("about2.research_text")),
          wlv_about_link("https://github.com/rodrigofranklin/wlvdb", l("about2.code_link"))),
        tags$div(class = "wlv-about-studies",
          tags$article(tags$h3(l("about2.method_title")), tags$p(l("about2.method_text")),
            wlv_about_link("https://doi.org/10.13169/worlrevipoliecon.13.3.0362", l("about2.method_link"))),
          tags$article(tags$h3(l("about2.applications_title")), tags$p(l("about2.applications_text")),
            tags$div(class = "wlv-about-study-links",
              wlv_about_link("https://econtents.sbu.unicamp.br/inpec/index.php/cma/article/view/18863", l("about2.brazil_link")),
              wlv_about_link("https://enep.sep.org.br/uploads/1316_1710722071_artigo-rev-borges_pdf_ide.pdf", l("about2.china_link")))))),
      tags$section(class = "wlv-about-team",
        tags$p(class = "wlv-about-kicker", l("about2.team_kicker")),
        tags$h2(l("about2.team_title")), tags$p(l("about2.team_text")),
        tags$div(class = "wlv-about-people",
          wlv_about_person("Rodrigo Straessli Pinto Franklin", "https://worldlabourvalues.org/equipe/franklin.html", "people/rodrigo-franklin.jpg"),
          wlv_about_person("Rodrigo Emmanuel Santana Borges", "https://worldlabourvalues.org/equipe/rodrigo_borges.html", "people/rodrigo-borges.gif", "wlv-about-portrait-white wlv-about-portrait-borges"),
          wlv_about_person("Mario César Sánchez", "https://www.uca.edu.sv/economia/cesar-sanchez/", "people/cesar-sanchez.jpg"),
          wlv_about_person("Everlam Elias Montibeler", "https://worldlabourvalues.org/equipe/ever.html", "people/everlam-montibeler.jpg")),
        wlv_about_link("https://worldlabourvalues.org/equipe.html", l("about2.team_link"))),
      tags$section(class = "wlv-about-institution",
        wlv_about_link("http://www.labcidades.com.br",
          tags$img(src = "branding/labcidades.webp", alt = "LabCidades", loading = "lazy"),
          class = "wlv-about-lab-logo"),
        tags$div(tags$p(class = "wlv-about-kicker", l("about2.institution_kicker")),
          tags$h2("LabCidades"), tags$p(l("about2.institution_text")),
          wlv_about_link("http://www.labcidades.com.br", l("about2.institution_link")))),
      wlv_citation_section())
  )
)
modules_ui[[length(modules_ui) + 1L]] <- TABPANEL
